import type { ToolConfig } from "./types";

export const TOOLS: ToolConfig[] = [
  // ─── PDF TOOLS ──────────────────────────────────────────────
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document",
    longDescription:
      "Combine multiple PDF files into a single document in seconds. Upload up to 20 PDFs, drag to reorder, then click Merge. 100% browser-based — your files never leave your device.",
    category: "pdf",
    icon: "FilePlus2",
    color: "#ef4444",
    gradient: "from-red-50 to-orange-50",
    acceptedTypes: "application/pdf",
    multiple: true,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["merge PDF", "combine PDF", "join PDF", "PDF merger", "merge PDF free", "combine PDF online"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Split a PDF into multiple files by page range",
    longDescription:
      "Extract specific pages or page ranges from any PDF file. Enter a range like 1–5 or individual pages like 1,4,7 and download the result as a new PDF. Works entirely in your browser.",
    category: "pdf",
    icon: "Scissors",
    color: "#f97316",
    gradient: "from-orange-50 to-yellow-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["split PDF", "separate PDF", "extract PDF pages", "PDF splitter", "split PDF online free"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce PDF file size without losing quality",
    longDescription:
      "Shrink your PDF file size by up to 80% while preserving readability. Choose Low, Medium, or High compression based on your needs. Runs locally in your browser — no upload required.",
    category: "pdf",
    icon: "PackageOpen",
    color: "#eab308",
    gradient: "from-yellow-50 to-lime-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["compress PDF", "reduce PDF size", "optimize PDF", "PDF compressor", "compress PDF online free", "smaller PDF"],
  },
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description: "Add your handwritten signature to PDF files",
    longDescription:
      "Draw, type, or upload your signature and place it anywhere on your PDF. Perfect for contracts, forms, and approvals. No Adobe Acrobat needed — works in any browser.",
    category: "pdf",
    icon: "PenLine",
    color: "#2563eb",
    gradient: "from-blue-50 to-indigo-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["sign PDF", "e-sign PDF", "electronic signature", "PDF signature", "sign PDF online free", "digital signature"],
  },
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description: "Extract text from scanned PDFs using OCR",
    longDescription:
      "Use Optical Character Recognition (OCR) to extract text from scanned documents or image-based PDFs. Download the detected text as a .txt file for editing or searching.",
    category: "pdf",
    icon: "Search",
    color: "#0ea5e9",
    gradient: "from-sky-50 to-cyan-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["OCR PDF", "scanned PDF to text", "extract text from PDF", "OCR online free", "PDF OCR", "searchable PDF"],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate PDF pages to the correct orientation",
    longDescription:
      "Fix sideways or upside-down pages in your PDF. Rotate all pages or select specific pages to rotate by 90°, 180°, or 270°. No quality loss — orientation metadata is updated instantly.",
    category: "pdf",
    icon: "RotateCcw",
    color: "#14b8a6",
    gradient: "from-teal-50 to-cyan-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["rotate PDF", "rotate PDF pages", "fix PDF orientation", "PDF rotate online free"],
  },
  {
    slug: "add-watermark",
    name: "Add Watermark",
    description: "Add text or image watermark to every PDF page",
    longDescription:
      "Protect or brand your PDF by adding a custom text or image watermark to every page. Control opacity, position, font, and color. Runs in your browser — no upload needed.",
    category: "pdf",
    icon: "Stamp",
    color: "#7c3aed",
    gradient: "from-violet-50 to-indigo-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["watermark PDF", "add watermark to PDF", "PDF watermark online free", "stamp PDF"],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description: "Remove password protection from a PDF file",
    longDescription:
      "Remove password restrictions from a PDF you own. Enter the current password to decrypt and download an unlocked copy of your PDF. Runs in the browser.",
    category: "pdf",
    icon: "LockOpen",
    color: "#059669",
    gradient: "from-emerald-50 to-green-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["unlock PDF", "remove PDF password", "decrypt PDF", "unlock PDF online free", "PDF unlocker"],
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Add password protection to your PDF file",
    longDescription:
      "Secure your PDF with AES-256 encryption. Set a password to prevent unauthorized access to your document. Entire process runs in your browser.",
    category: "pdf",
    icon: "ShieldCheck",
    color: "#dc2626",
    gradient: "from-red-50 to-rose-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["protect PDF", "password protect PDF", "encrypt PDF", "secure PDF online free", "PDF password"],
  },
  {
    slug: "pdf-page-numbers",
    name: "PDF Page Numbers",
    description: "Add page numbers to any PDF document",
    longDescription:
      "Insert auto-incrementing page numbers anywhere in your PDF — header, footer, corners. Customize font, size, position, and starting number. Runs locally in your browser.",
    category: "pdf",
    icon: "Hash",
    color: "#ea580c",
    gradient: "from-orange-50 to-amber-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["PDF page numbers", "add page numbers to PDF", "number PDF pages", "PDF numbering online free"],
  },
  {
    slug: "extract-pdf-pages",
    name: "Extract PDF Pages",
    description: "Extract specific pages from a PDF into a new file",
    longDescription:
      "Select individual pages or page ranges to extract from any PDF. Download the extracted pages as a brand new PDF file instantly. Runs entirely in your browser.",
    category: "pdf",
    icon: "FileOutput",
    color: "#7c3aed",
    gradient: "from-violet-50 to-purple-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["extract PDF pages", "pull pages from PDF", "select pages PDF", "extract pages from PDF free"],
  },
  {
    slug: "reorder-pdf-pages",
    name: "Reorder PDF Pages",
    description: "Drag and drop to rearrange pages in your PDF",
    longDescription:
      "Visually rearrange the page order of your PDF. Drag and drop thumbnails to reorganize your document exactly how you want it. Download the reordered PDF instantly.",
    category: "pdf",
    icon: "GripVertical",
    color: "#0891b2",
    gradient: "from-cyan-50 to-sky-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["reorder PDF pages", "rearrange PDF pages", "reorganize PDF", "sort PDF pages free"],
  },
  {
    slug: "fill-pdf-form",
    name: "Fill PDF Form",
    description: "Fill out PDF forms online without Adobe Acrobat",
    longDescription:
      "Fill in PDF form fields directly in your browser — text fields, checkboxes, dropdowns. Download the completed form as a PDF. No Adobe Acrobat, no software needed.",
    category: "pdf",
    icon: "PenLine",
    color: "#b45309",
    gradient: "from-amber-50 to-yellow-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["fill PDF form", "fillable PDF", "PDF form filler", "fill PDF online free", "complete PDF form"],
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    description: "Add text, highlights, and shapes to any PDF",
    longDescription:
      "Annotate your PDF in the browser. Add text labels, highlight regions, or draw colored shapes on any page. No software needed — 100% private and browser-based.",
    category: "pdf",
    icon: "Edit3",
    color: "#f97316",
    gradient: "from-orange-50 to-amber-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["edit PDF", "PDF editor online free", "annotate PDF", "highlight PDF", "add text to PDF", "draw on PDF"],
  },
  {
    slug: "edit-word",
    name: "Edit Word",
    description: "Edit Word documents online without Microsoft Word",
    longDescription:
      "Upload a Word document (.docx) and edit its text, formatting, and layout in a rich-text editor — then save it back to your device. No Microsoft Word or subscription needed.",
    category: "pdf",
    icon: "FileText",
    color: "#2563eb",
    gradient: "from-blue-50 to-indigo-50",
    acceptedTypes: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["edit Word document", "online Word editor", "edit docx online free", "Word editor no signup"],
  },

  // ─── IMAGE TOOLS ────────────────────────────────────────────
  {
    slug: "compress-image",
    name: "Image Compressor",
    description: "Compress images without losing quality",
    longDescription:
      "Compress JPG, PNG, and WebP images with adjustable quality settings. Reduce image file size by up to 80% while maintaining excellent visual quality. Batch compress up to 20 images at once.",
    category: "image",
    icon: "Minimize2",
    color: "#8b5cf6",
    gradient: "from-violet-50 to-purple-50",
    acceptedTypes: "image/*",
    multiple: true,
    maxFileSize: 30 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["compress image", "image compressor online", "reduce image size free", "compress JPG online", "compress PNG online", "image optimizer"],
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    description: "Resize images to exact pixel dimensions",
    longDescription:
      "Resize images to exact pixel dimensions or scale by percentage. Supports JPG, PNG, WebP, and more. Batch resize multiple images at once. Instant result with no quality loss.",
    category: "image",
    icon: "Maximize2",
    color: "#0891b2",
    gradient: "from-cyan-50 to-teal-50",
    acceptedTypes: "image/*",
    multiple: true,
    maxFileSize: 30 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["resize image online", "image resizer free", "change image size", "resize JPG online", "resize PNG free", "image dimensions"],
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    description: "Crop images to any size or aspect ratio",
    longDescription:
      "Crop your images with an interactive drag-and-drop cropper. Choose free-form cropping or lock to popular aspect ratios like 1:1, 16:9, and 4:3. Works with all major image formats.",
    category: "image",
    icon: "Crop",
    color: "#65a30d",
    gradient: "from-lime-50 to-green-50",
    acceptedTypes: "image/*",
    multiple: false,
    maxFileSize: 30 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["crop image online", "image cropper free", "crop photo online", "crop image to size", "crop JPG online"],
  },
  {
    slug: "remove-bg",
    name: "Remove Background",
    description: "Remove image background automatically online",
    longDescription:
      "Automatically remove the background from photos with one click. Get a transparent PNG perfect for product images, profile photos, and design work. No Photoshop needed.",
    category: "image",
    icon: "Eraser",
    color: "#be185d",
    gradient: "from-pink-50 to-fuchsia-50",
    acceptedTypes: "image/*",
    multiple: false,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["remove background online free", "background remover", "transparent background", "remove image background", "cut out image", "no watermark"],
  },
  {
    slug: "passport-photo",
    name: "Passport Photo",
    description: "Create passport photos in official standard sizes",
    longDescription:
      "Upload your photo and generate a correctly cropped and sized passport photo for US, UK, EU, or other standards. Download a print-ready file with multiple photos per sheet.",
    category: "image",
    icon: "Camera",
    color: "#ec4899",
    gradient: "from-pink-50 to-rose-50",
    acceptedTypes: "image/*",
    multiple: false,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["passport photo maker", "passport photo size online", "ID photo maker free", "visa photo size", "US passport photo size"],
  },
  {
    slug: "add-text-to-image",
    name: "Add Text to Image",
    description: "Add captions, labels, or watermarks to images",
    longDescription:
      "Add custom text to any image with full control over font, size, color, position, and opacity. Perfect for memes, captions, labels, social media graphics, and watermarks.",
    category: "image",
    icon: "Type",
    color: "#be185d",
    gradient: "from-pink-50 to-rose-50",
    acceptedTypes: "image/*",
    multiple: false,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["add text to image online free", "image text editor", "caption photo online", "meme generator", "label image", "text on photo"],
  },
  {
    slug: "flip-image",
    name: "Flip Image",
    description: "Flip or mirror images horizontally or vertically",
    longDescription:
      "Mirror any image horizontally (left-right flip) or vertically (top-bottom flip). Works with JPG, PNG, and WebP. Instant result with no quality loss.",
    category: "image",
    icon: "FlipHorizontal",
    color: "#0891b2",
    gradient: "from-cyan-50 to-teal-50",
    acceptedTypes: "image/*",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["flip image online", "mirror image free", "flip photo horizontally", "flip image vertically", "mirror photo"],
  },

  // ─── CONVERT TOOLS ──────────────────────────────────────────
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert JPG, PNG, or WebP images to a PDF",
    longDescription:
      "Convert one or multiple images (JPG, PNG, WebP) into a PDF document. Upload up to 30 images, arrange their order, and download a PDF with each image on a separate page.",
    category: "convert",
    icon: "ImageIcon",
    color: "#22c55e",
    gradient: "from-green-50 to-emerald-50",
    acceptedTypes: "image/*",
    multiple: true,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 30,
    isPremium: false,
    freeLimit: 0,
    tags: ["image to PDF", "JPG to PDF", "PNG to PDF", "convert image to PDF free", "photo to PDF", "images to PDF converter"],
  },
  {
    slug: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to PNG or JPEG images",
    longDescription:
      "Convert each page of your PDF into a high-quality PNG or JPEG image. Choose your preferred output format and download all images as a ZIP file. Runs in your browser.",
    category: "convert",
    icon: "FileImage",
    color: "#06b6d4",
    gradient: "from-cyan-50 to-sky-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["PDF to image", "PDF to PNG", "PDF to JPEG", "convert PDF to image free", "PDF to JPG online"],
  },
  {
    slug: "png-to-jpeg",
    name: "PNG to JPEG",
    description: "Convert PNG images to JPEG format",
    longDescription:
      "Convert PNG files to JPEG with adjustable quality. Transparent backgrounds are automatically filled with white. Batch convert up to 20 images at once.",
    category: "convert",
    icon: "ArrowLeftRight",
    color: "#3b82f6",
    gradient: "from-blue-50 to-indigo-50",
    acceptedTypes: "image/png",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["PNG to JPEG", "PNG to JPG converter", "convert PNG to JPEG free", "PNG to JPG online"],
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    description: "Convert JPG/JPEG images to lossless PNG",
    longDescription:
      "Convert JPG or JPEG files to PNG for lossless quality. Great when you need transparent output or design workflows that require PNG. Batch convert multiple files at once.",
    category: "convert",
    icon: "ArrowLeftRight",
    color: "#22c55e",
    gradient: "from-green-50 to-emerald-50",
    acceptedTypes: ".jpg,.jpeg,image/jpeg,image/jpg",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["JPG to PNG", "JPEG to PNG converter", "convert JPG to PNG free", "JPG to PNG online"],
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    description: "Convert WebP images to JPG/JPEG format",
    longDescription:
      "Convert WebP files to JPEG for compatibility with apps and platforms that don't support WebP. Batch convert up to 20 files. Instant result in your browser.",
    category: "convert",
    icon: "ArrowLeftRight",
    color: "#f97316",
    gradient: "from-orange-50 to-amber-50",
    acceptedTypes: ".webp,image/webp",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["WebP to JPG", "WebP to JPEG converter", "convert WebP to JPG free", "WebP converter online"],
  },
  {
    slug: "webp-to-png",
    name: "WebP to PNG",
    description: "Convert WebP images to lossless PNG",
    longDescription:
      "Convert WebP files to PNG for design workflows and editing tools that prefer PNG format. Retains full image quality. Batch convert multiple WebP files at once.",
    category: "convert",
    icon: "ArrowLeftRight",
    color: "#06b6d4",
    gradient: "from-cyan-50 to-sky-50",
    acceptedTypes: ".webp,image/webp",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["WebP to PNG", "convert WebP to PNG free", "WebP to PNG online"],
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert SVG vector graphics to PNG images",
    longDescription:
      "Convert SVG files to high-resolution PNG images. Choose your output size for pixel-perfect results. Ideal for sharing or uploading where SVG is not supported.",
    category: "convert",
    icon: "FileImage",
    color: "#0ea5e9",
    gradient: "from-sky-50 to-blue-50",
    acceptedTypes: ".svg,image/svg+xml",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["SVG to PNG", "convert SVG to PNG free", "SVG to PNG online", "vector to image"],
  },
  {
    slug: "svg-to-jpg",
    name: "SVG to JPG",
    description: "Convert SVG vector graphics to JPG",
    longDescription:
      "Convert SVG files to JPG for lightweight image sharing and broad compatibility with apps that don't render SVG.",
    category: "convert",
    icon: "FileImage",
    color: "#f59e0b",
    gradient: "from-amber-50 to-yellow-50",
    acceptedTypes: ".svg,image/svg+xml",
    multiple: true,
    maxFileSize: 20 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["SVG to JPG", "convert SVG to JPEG free", "SVG to JPG online", "vector to JPG"],
  },
  {
    slug: "gif-to-mp4",
    name: "GIF to MP4",
    description: "Convert animated GIF files to MP4 video",
    longDescription:
      "Convert GIF animations to MP4 for dramatically smaller file sizes and smoother playback on social media and messaging apps. Fast server-side conversion.",
    category: "convert",
    icon: "Video",
    color: "#16a34a",
    gradient: "from-green-50 to-lime-50",
    acceptedTypes: ".gif,image/gif",
    multiple: false,
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["GIF to MP4", "convert GIF to MP4 free", "GIF to video", "GIF to MP4 online"],
  },
  {
    slug: "mp4-to-gif",
    name: "MP4 to GIF",
    description: "Convert MP4 video clips to animated GIF",
    longDescription:
      "Convert short MP4 video clips to GIF animations for social media, messaging, and quick previews. Adjust start time and duration. Fast server-side conversion.",
    category: "convert",
    icon: "Video",
    color: "#8b5cf6",
    gradient: "from-violet-50 to-purple-50",
    acceptedTypes: ".mp4,video/mp4",
    multiple: false,
    maxFileSize: 150 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["MP4 to GIF", "convert MP4 to GIF free", "video to GIF", "MP4 to GIF online"],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents to PDF online free",
    longDescription:
      "Convert .doc or .docx files to professionally formatted PDF while preserving fonts, images, tables, and layout. Uses server-side conversion for perfect results.",
    category: "convert",
    icon: "FileText",
    color: "#2563eb",
    gradient: "from-blue-50 to-sky-50",
    acceptedTypes: ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["Word to PDF", "DOCX to PDF", "convert Word to PDF free", "Word to PDF online", ".docx to PDF"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents",
    longDescription:
      "Extract text and formatting from any PDF and convert it to an editable Word (.docx) document. Preserves heading structure and paragraph formatting. Fast server-side conversion.",
    category: "convert",
    icon: "FileOutput",
    color: "#0ea5e9",
    gradient: "from-sky-50 to-blue-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["PDF to Word", "PDF to DOCX", "convert PDF to Word free", "PDF to Word online", "editable Word from PDF"],
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract PDF tables to editable Excel spreadsheets",
    longDescription:
      "Extract tables and data from PDF files and convert them into editable Excel (.xlsx) spreadsheets. Perfect for finance, accounting, and data workflows. Fast server-side conversion.",
    category: "convert",
    icon: "FileOutput",
    color: "#16a34a",
    gradient: "from-green-50 to-emerald-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["PDF to Excel", "PDF to XLSX", "convert PDF to Excel free", "extract table from PDF", "PDF to spreadsheet"],
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description: "Convert PDF to editable PowerPoint presentation",
    longDescription:
      "Convert each PDF page into an editable PowerPoint slide. Download a fully editable .pptx file ready for Microsoft PowerPoint, Google Slides, or LibreOffice Impress.",
    category: "convert",
    icon: "FileOutput",
    color: "#dc2626",
    gradient: "from-red-50 to-rose-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["PDF to PowerPoint", "PDF to PPTX", "convert PDF to PowerPoint free", "PDF to slides", "PDF to presentation"],
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    description: "Convert plain text or notes to a formatted PDF",
    longDescription:
      "Type or paste any text and convert it to a beautifully formatted PDF. Choose font size, margins, and page size (A4/Letter). Also supports uploading a .txt file for conversion.",
    category: "convert",
    icon: "FileText",
    color: "#059669",
    gradient: "from-emerald-50 to-green-50",
    acceptedTypes: "",
    multiple: false,
    maxFileSize: 0,
    maxFiles: 0,
    isPremium: false,
    freeLimit: 0,
    tags: ["text to PDF", "TXT to PDF", "convert text to PDF free", "notes to PDF", "plain text to PDF"],
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all readable text content from a PDF",
    longDescription:
      "Extract all readable text from any PDF document. Copy the text to your clipboard or download as a .txt file. Great for repurposing PDF content or making it searchable.",
    category: "convert",
    icon: "FileText",
    color: "#ea580c",
    gradient: "from-orange-50 to-amber-50",
    acceptedTypes: "application/pdf",
    multiple: false,
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    freeLimit: 0,
    tags: ["PDF to text", "extract text from PDF free", "PDF to TXT", "copy text from PDF", "PDF text extractor"],
  },
  {
    slug: "image-to-webp",
    name: "Image to WebP",
    description: "Convert images to WebP for faster websites",
    longDescription:
      "Convert PNG, JPEG, or GIF images to the modern WebP format. WebP is 25–35% smaller than JPEG/PNG at the same quality — perfect for faster web performance and better Core Web Vitals.",
    category: "convert",
    icon: "ImageIcon",
    color: "#7c3aed",
    gradient: "from-violet-50 to-purple-50",
    acceptedTypes: "image/*",
    multiple: true,
    maxFileSize: 30 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["image to WebP", "convert to WebP free", "JPG to WebP", "PNG to WebP", "WebP converter online", "optimize images for web"],
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPEG format",
    longDescription:
      "Convert Apple iPhone HEIC/HEIF photos to standard JPEG format. HEIC files aren't compatible everywhere — convert them instantly for universal device and app compatibility.",
    category: "convert",
    icon: "ImageIcon",
    color: "#16a34a",
    gradient: "from-green-50 to-emerald-50",
    acceptedTypes: ".heic,.heif,image/heic,image/heif",
    multiple: true,
    maxFileSize: 30 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    freeLimit: 0,
    tags: ["HEIC to JPG", "HEIC to JPEG converter", "convert HEIC to JPG free", "iPhone photo converter", "HEIF to JPG online"],
  },

  // ─── UTILITY TOOLS ──────────────────────────────────────────
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, WiFi, and more",
    longDescription:
      "Create professional QR codes instantly. Supports URLs, plain text, WiFi credentials, email, and phone numbers. Customize colors, size, and error correction. Download as PNG or SVG.",
    category: "utility",
    icon: "QrCode",
    color: "#1d4ed8",
    gradient: "from-blue-50 to-indigo-50",
    acceptedTypes: "",
    multiple: false,
    maxFileSize: 0,
    maxFiles: 0,
    isPremium: false,
    freeLimit: 0,
    tags: ["QR code generator free", "create QR code", "QR code maker", "QR code for URL", "WiFi QR code", "free QR code online"],
  },
];

// ---- Helper functions ----

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolConfig["category"]): ToolConfig[] {
  return TOOLS.filter((t) => t.category === category);
}

export function searchTools(query: string): ToolConfig[] {
  const q = query.toLowerCase().trim();
  if (!q) return TOOLS;
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
  );
}

export const CATEGORY_META: Record<
  ToolConfig["category"],
  { label: string; description: string; color: string }
> = {
  pdf: {
    label: "PDF Tools",
    description: "Merge, split, compress, sign, protect and convert PDF files",
    color: "red",
  },
  image: {
    label: "Image Tools",
    description: "Compress, resize, crop, remove backgrounds and convert images",
    color: "purple",
  },
  convert: {
    label: "Convert",
    description: "Convert between PDF, Word, Excel, images, and video formats",
    color: "blue",
  },
  utility: {
    label: "Utilities",
    description: "QR codes, text tools and other handy utilities",
    color: "gray",
  },
};
